/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomFilter } from './CustomFilter';
import {
    CustomFilterFromJSON,
    CustomFilterFromJSONTyped,
    CustomFilterToJSON,
    CustomFilterToJSONTyped,
} from './CustomFilter';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * Adds nested create feature
 * @export
 * @interface RecipeBook
 */
export interface RecipeBook {
    /**
     * 
     * @type {number}
     * @memberof RecipeBook
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RecipeBook
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeBook
     */
    description?: string;
    /**
     * 
     * @type {Array<User>}
     * @memberof RecipeBook
     */
    shared: Array<User>;
    /**
     * 
     * @type {User}
     * @memberof RecipeBook
     */
    readonly createdBy: User;
    /**
     * 
     * @type {CustomFilter}
     * @memberof RecipeBook
     */
    filter?: CustomFilter | null;
    /**
     * 
     * @type {number}
     * @memberof RecipeBook
     */
    order?: number;
    /**
     * home fork: 'cookbook' (printed) or 'collection'
     * @type {string}
     * @memberof RecipeBook
     */
    kind?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeBook
     */
    author?: string;
    /**
     * cover image URL, set through the cover action
     * @type {string}
     * @memberof RecipeBook
     */
    readonly cover?: string | null;
}

/**
 * Check if a given object implements the RecipeBook interface.
 */
export function instanceOfRecipeBook(value: object): value is RecipeBook {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('shared' in value) || value['shared'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    return true;
}

export function RecipeBookFromJSON(json: any): RecipeBook {
    return RecipeBookFromJSONTyped(json, false);
}

export function RecipeBookFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeBook {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'shared': ((json['shared'] as Array<any>).map(UserFromJSON)),
        'createdBy': UserFromJSON(json['created_by']),
        'filter': json['filter'] == null ? undefined : CustomFilterFromJSON(json['filter']),
        'order': json['order'] == null ? undefined : json['order'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'author': json['author'] == null ? undefined : json['author'],
        'cover': json['cover'] == null ? undefined : json['cover'],
    };
}

export function RecipeBookToJSON(json: any): RecipeBook {
    return RecipeBookToJSONTyped(json, false);
}

export function RecipeBookToJSONTyped(value?: Omit<RecipeBook, 'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'shared': ((value['shared'] as Array<any>).map(UserToJSON)),
        'filter': CustomFilterToJSON(value['filter']),
        'order': value['order'],
        'kind': value['kind'],
        'author': value['author'],
    };
}

